name: PMD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        java-version: 14
        
    - name: Setup Maven
      run: |
        echo "export PATH=${PATH}:/usr/local/maven/bin" >> ${HOME}/.bashrc
        . ${HOME}/.bashrc
    - name: Build and Test
      run: mvn clean install
    - name: PMD
      run: mvn pmd:pmd -Dpmd.rulesets=file:pmd-ruleset.xml -Dpmd.render.xml=false
    - name: Save PMD report
      run: |
        mkdir -p pmd-report
        cp target/pmd.xml pmd-report/pmd.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

